# This file is auto-generated and contains the integrals that were answered incorrectly.
QUESTIONS_INCORRECT = [
    'integrate(1/(x**2 - 2*x + 3), x)',
    'integrate(x/(x**2 + 1), x)',
    'integrate(sin(x)**2, x)',
    'integrate(cos(x)**2, x)',
    'integrate(exp(x)*sin(x), x)',
    'integrate(exp(x)*cos(x), x)',
    'integrate(1/(1 + x**2)**2, x)',
    'integrate(1/sqrt(1 - x**2), x)',
    'integrate(1/sqrt(x**2 - 1), x)',
    'integrate(x**2*exp(x), x)',
    'integrate(x*log(x), x)',
    'integrate((2*x + 1)/(x**2 + x + 1), x)',
    'integrate((x + 1)/(x**2 + 2*x + 2), x)',
    'integrate(sin(x)/cos(x), x)',
    'integrate(cos(x)/sin(x), x)',
    'integrate(1/(1 + sin(x)), x)',
    'integrate(1/(1 + cos(x)), x)',
    'integrate(tan(x), x)',
    'integrate(sec(x)**2, x)',
    'integrate(x/(x**2 - 4), x)',
    'integrate(1/((x - 1)*(x + 2)), x)',
    'integrate(x**3/(x**2 + 1), x)',
    'integrate(1/sqrt(x**2 + 4), x)',
    'integrate(1/(x**3 + 1), x)',
    'integrate((x**2 + 1)/(x**2 - 1), x)',
    'integrate((x**2 + 1)/(x**3 + 3*x + 2), x)',
    'integrate((sqrt(x + 2) - sqrt(x))/(sqrt(x + 2) + sqrt(x)), x)',
    'integrate(x*exp(x)/(1 + exp(2*x)), x)',
    'integrate(x/(sqrt(x) + 1), x)',
    'integrate((x**2 - 2*x + 2)/(x**2 + 1), x)',
    'integrate(sin(x)*cos(x)/(1 + sin(x)**2), x)',
    'integrate((1 - cos(x))/x, x)',
    'integrate(x/(1 + x**4), x)',
    'integrate((x - 1)/(x**2 + 2*x + 2), x)',
    'integrate(log(x)/x**2, x)',
    'integrate((x**2 + 1)/(x**2 - 1), x)',
    'integrate(1/(x**3 + x), x)',
    'integrate((x + 1)/(x**2 + 2*x + 2), x)',
    'integrate(sin(x)/(cos(x) + 1), x)',
    'integrate(cos(x)/(sin(x) + 1), x)',
    'integrate(1/sqrt(1 + x**2), x)',
    'integrate(x/sqrt(x**2 + 4), x)',
    'integrate(sin(x)**2/(cos(x) + 2), x)',
    'integrate(cos(x)**2/(sin(x) + 2), x)',
    'integrate(exp(x)/(exp(x) + 1), x)',
    'integrate((x**3 + 1)/(x**2 + 1), x)',
    'integrate(x*sqrt(x**2 + 1), x)',
    'integrate(log(x)/(1 + x), x)',
    'integrate(x*log(1 + x)/(1 + x**2), x)',
    'integrate((x - 2)/(x**2 + 4*x + 5), x)',
    'integrate(1/(x*sqrt(x**2 - 1)), x)',
    'integrate((sqrt(x + 1) - sqrt(x))/x, x)',
    'integrate(x**2/(x**3 + 1), x)',
    'integrate(1/((x+1)**2 + 4), x)',
    'integrate(x*exp(2*x), x)',
    'integrate(x*sin(x), x)',
    'integrate(x*ln(x), x)',
    'integrate(ln(x)/x**2, x)',
    'integrate((2*x+1)/(x**2+x+1), x)',
    'integrate((x-1)/(x**2-1), x)',
    'integrate(1/(x*sqrt(x**2-1)), x)',
    'integrate(1/sqrt(x**2+9), x)',
    'integrate((x**3+2*x**2+1)/(x+1), x)',
    'integrate(x/(x**2+4), x)',
    'integrate(1/(x**4+1), x)',
    'integrate(cos(x)/(1+sin(x)), x)',
    'integrate(sin(x)/(1+cos(x)), x)',
    'integrate(1/(1+x**(1/3)), x)',
    'integrate(1/(sqrt(x)*(1+sqrt(x))**2), x)',
    'integrate((x**2-1)/(x**2+1), x)',
    'integrate((x+2)/(x**2+2*x+2), x)',
    'integrate((x-2)/(x**2-2*x+2), x)',
    'integrate(x*exp(x**2), x)',
    'integrate((2*x)/(1+x**2)**2, x)',
    'integrate((x-3)/(x**2-3*x+5), x)',
    'integrate(1/((x**2+1)*(x+1)), x)',
    'integrate((2*x+3)/(x**2+3*x+5), x)',
    'integrate((x**2+2*x+1)/(x**2+4), x)',
    'integrate((sqrt(x+3)-sqrt(x))/x, x)',
    'integrate(x/(x**2+4), x)',
    'integrate(1/(x**2+x+1), x)',
    'integrate(x**2/(x**3+1), x)',
    'integrate((x+1)/(x**2+2*x+2), x)',
    'integrate((x-1)/(x**2-2*x+2), x)',
    'integrate(1/(sqrt(x)*(1+sqrt(x))), x)',
    'integrate(sin(x)**2, x)',
    'integrate(cos(x)**2, x)',
    'integrate(sin(x)/cos(x), x)',
    'integrate(cos(x)/sin(x), x)',
    'integrate(tan(x), x)',
    'integrate(sec(x)**2, x)',
    'integrate(csc(x)**2, x)',
    'integrate(sec(x)*tan(x), x)',
    'integrate(csc(x)*cot(x), x)',
    'integrate(exp(x)/(1+exp(x)), x)',
    'integrate(log(x)/x, x)',
    'integrate(x*log(x), x)',
    'integrate((log(x))**2, x)',
    'integrate((1-cos(x))/x**2, x)',
    'integrate(x*sin(x), x)',
    'integrate(x*cos(x), x)',
    'integrate(x*exp(x), x)',
    'integrate(x**2*exp(x), x)',
    'integrate(exp(-x)*sin(x), x)',
    'integrate(exp(-x)*cos(x), x)',
    'integrate(1/(1+x**4), x)',
    'integrate(x/(1+x**4), x)',
    'integrate(1/(x**3+1), x)',
    'integrate(1/(x**3-1), x)',
    'integrate((x**2+1)/(x**2-1), x)',
    'integrate((x**2-1)/(x**2+1), x)',
    'integrate(1/(x*(log(x))**2), x)',
    'integrate(x/(x**2+1), x)',
    'integrate(1/(x**2+1), x)',
    'integrate(1/sqrt(1+x**2), x)',
    'integrate(sqrt(1+x**2), x)',
    'integrate(1/(x**2*sqrt(x**2-1)), x)',
    'integrate(x/sqrt(x**2-1), x)',
    'integrate(sqrt(x**2-1), x)',
    'integrate(1/(sqrt(x-1)+sqrt(x+1)), x)',
    'integrate((sqrt(x+1)-sqrt(x))/(sqrt(x+1)+sqrt(x)), x)',
    'integrate(x/(sqrt(x+1)+sqrt(x)), x)',
    'integrate(1/(x**2+2*x+2), x)',
    'integrate((x+1)/(x**2+2*x+2), x)',
    'integrate(1/((x+1)**2+4), x)',
    'integrate(x/((x+1)**2+4), x)',
    'integrate((2*x+1)/(x**2+x+2), x)',
    'integrate((x**2+2*x+3)/(x**2+4*x+5), x)',
    'integrate(1/(x**2-4), x)',
    'integrate(1/(x**2-2*x), x)',
    'integrate(x/(x**2-2*x), x)',
    'integrate((x-2)/(x**2-4), x)',
    'integrate((x+2)/(x**2+2*x+2), x)',
    'integrate(x**2/sqrt(x**2+9), x)',
    'integrate(x/sqrt(x**2+9), x)',
    'integrate(sqrt(x**2+9), x)',
    'integrate(x/sqrt(9-x**2), x)',
    'integrate(sqrt(9-x**2), x)',
    'integrate((x**2+3)/(x**3+3*x), x)',
    'integrate((x**2-3)/(x**3-3*x), x)',
    'integrate((x-1)/(x**3+1), x)',
    'integrate((x+1)/(x**3-1), x)',
    'integrate((x**2+1)/(x**4+1), x)',
    'integrate((x**3+1)/(x**2+1), x)',
    'integrate(x*atan(x), x)',
    'integrate(atan(x)/x, x)',
    'integrate(atan(x)/(1+x**2), x)',
    'integrate(x*asin(x), x)',
    'integrate(acos(x)/sqrt(1-x**2), x)',
    'integrate(x*acos(x), x)',
    'integrate(sinh(x)/cosh(x), x)',
    'integrate(1/cosh(x), x)',
    'integrate(1/sinh(x), x)',
    'integrate(exp(x)/(exp(x)+exp(-x)), x)',
    'integrate((exp(x)-exp(-x))/(exp(x)+exp(-x)), x)',
    'integrate(x**3*exp(-x**2), x)',
    'integrate(x**2*log(x), x)',
    'integrate(x*log(x)**2, x)',
    'integrate(log(x)/(x+1), x)',
    'integrate((x+1)*exp(x)/(x**2+1), x)',
    'integrate((2*x+1)*exp(x)/(x**2+1), x)',
    'integrate(cos(x)*log(x), x)',
    'integrate((x**3+2*x)/(x**2+1), x)',
    'integrate((x**4+1)/(x**2+2), x)',
]

HARDEST_INTEGRALS = [
    'integrate(x*exp(x**2), x)',
    'integrate((sqrt(x+3)-sqrt(x))/x, x)',
    'integrate(1/(sqrt(x)*(1+sqrt(x))**2), x)',
    'integrate(x*log(1 + x)/(1 + x**2), x)',
    'integrate(1/(x*sqrt(x**2 - 1)), x)',
    'integrate((sqrt(x + 1) - sqrt(x))/x, x)',
    'integrate(1/((x+1)**2 + 4), x)',
    'integrate(x**3*exp(-x**2), x)',
    'integrate(x*log(x)**2, x)',
    'integrate((x**4+1)/(x**2+2), x)',
]
