"""
base_questions.py

This file contains a list of base integral problems that are considered challenging.
Each problem is represented as a string which we expect to follow the pattern:
    integrate(<integrand>, x)
For example: "integrate(1/(x**2 - x + 1), x)"
"""

#2020 - 2024 MIT intergration bee questions
#https://math.mit.edu/~yyao1/integrationbee.html
#just the qualifier tests

BASE_QUESTIONS = [
    "integrate(1/(x**2 - 2*x + 3), x)",
    "integrate(2025/(2023*2024), x)",
    "integrate((x - 1)*log(x+1)/(x + 1)/log(x-1), x)",
    "integrate(x*log(x) + 2*x, x)",
    "integrate(1/(x*log(x) + 2*x), x)",
    "integrate(arccos(sin(x)), x)",
    "integrate((cos(x) + cot(x) + csc(x) + 1)/(sin(x) + tan(x) + sec(x) + 1), x)",
    "integrate(x/(x**2024 - 1)/(x**506 - 1), x)",
    "integrate((5*x**3 - 3*x)**2, x)",
    "integrate((sin(x) + cos(x))**11, x)",
    "integrate((sinh(x) + cosh(x))**11, x)",
    "integrate(csc(x)**2 * tan(x)**2024, x)",
    "integrate(cos(x)*(log(cos(x)) - x*tan(x)), x)",
    "integrate(exp(-(x-2024)**2/4), x)",
    "integrate((1 - 1/x**2)*exp(x+1/x), x)",
    "integrate((x + 1 - exp(-x))*exp(x*exp(x)), x)",
    "integrate((arctan(x)/(1-x**2) + arctanh(x)/(1+x**2)), x)",
    "integrate(sum(sin(k*pi/2)*x/factorial(k), (k, 0, oo)), x)",
    "integrate(sum(x**(2*n-1012), (n, 0, 2024)), x)",
    "integrate(x**4/(3 - 6*x + 6*x**2 - 4*x**3 + 2*x**4), x)",
    "integrate(x + ContinuedFraction([1, x, 1, x]), x)",
    "integrate(x*log(x), x)",
    "integrate(sech(x), x)",
    "integrate(exp(x)*(1 + exp(x))*log(1 + exp(x)), x)",
    "integrate((1 + x + x**2 + x**3 + x**4)*(1 - x + x**2 - x**3 + x**4), x)",
    "integrate(x**5, x)",
    "integrate(x + sin(x) + x*cos(x) + sin(x)*cos(x), x)",
    "integrate(sin(x)**2 + cos(x)**2 + tan(x)**2 + cot(x)**2 + sec(x)**2 + csc(x)**2, x)",
    "integrate(floor(2023*sin(x)), x)",
    "integrate((2*log(x) + 1)*exp(log(x)**2), x)",
    "integrate((1 - x)**3 + (x - x**2)**3 + (x**2 - 1)**3 - 3*(1 - x)*(x - x**2)*(x**2 - 1), x)",
    "integrate(Abs(Abs(Abs(Abs(x) - 1) - 1) - 1), x)",
    "integrate(sin(x)**6 + cos(x)**6 + 3*sin(x)**2*cos(x)**2, x)",
    "integrate((x + E + 1)**x*exp(x), x)",
    "integrate(sqrt(2*x/(x + 1))/(2 - x**2), x)",
    "integrate((1 + 2*x**2022)/(x + x**2023), x)",
    "integrate(3*sin(20*x)*cos(23*x) + 20*sin(43*x), x)",
    "integrate(Product(1/(1 + x**(2**k)), (k, 0, oo)), x)",
    "integrate(sin(x)/(2*exp(x) + cos(x) + sin(x)), x)",
    "integrate(log(x/pi)/(log(x)**log(pi*E)), x)",
    "integrate(x**5 + 5*x**4 + 10*x**3 + 8*x**2 + x, x)",
    "integrate((1 + cos(x))/(x + sin(x)), x)",
    "integrate((arctan(x) + arccot(x))/x, x)",
    "integrate(x**2 - floor(x)*ceiling(x), x)",
    "integrate(sinh(x)/(cosh(x) - sinh(x)), x)",
    "integrate(x/(sqrt(x - 1) + sqrt(x + 1)), x)",
    "integrate(cos(x + cos(x)), x)",
    "integrate(x**3*sin(x**2), x)",
    "integrate(x/(1 - x**4), x)",
    "integrate(1/cosh(x)**2, x)",
    "integrate(exp(exp(x)) - exp(exp(x) - x), x)",
    "integrate(Limit(sin(pi/3)*sin(pi/3)*sin(pi/3)*x, n, oo), x)",
    "integrate(sqrt(1 - sqrt(x)), x)",
    "integrate(x**3/(1 + x + x**2/2 + x**3/6), x)",
    "integrate(sin(x + sin(x)) - sin(x - sin(x)), x)",
    "integrate(tan(x)**4*sec(x)**3 + tan(x)**2*sec(x)**5, x)",
    "integrate((1 + log(x))*log(log(x)), x)",
    "integrate(1/(1 + sin(x)) + 1/(1 + cos(x)) + 1/(1 + tan(x)) + 1/(1 + cot(x)) + 1/(1 + sec(x)) + 1/(1 + csc(x)), x)",
    "integrate(1/sqrt(x - x**2), x)",
    "integrate(sum(binomial(n + 3, n)*x**n, (n, 0, oo)), x)",
    "integrate(1/(1 + cos(x)**2), x)",
    "integrate(log(2*x)/(x*log(x)), x)",
    "integrate(1/(exp(x) + 1), x)",
    "integrate(log(x)*log(log(x))/x, x)",
    "integrate(log((1 + x)/(1 - x)), x)",
    "integrate(1/(x**2 + (x - 1)**2), x)",
    "integrate(sqrt(x*sqrt(x*sqrt(x))), x)",
    "integrate(sin(x)**4*cos(x)**4*(cos(x) + sin(x))*(cos(x) - sin(x)), x)",
    "integrate(log(x**2 + 1), x)",
    "integrate(cos(x)**(2020), x)",
    "integrate((2*x + 1)/(2*x**2 + 2*x + 1), x)",
    "integrate(arcsin(x)/x**3, x)",
    "integrate(sin(2*x)*cos(cos(x)), x)",
    "integrate(sin(sin(x) - x), x)",
    "integrate(1/(x - 1) + sum((k + 1)*x**k, (k, 0, 2018))/sum(x**k, (k, 0, 2019)), x)",
    "integrate(1/(tan(x)**(sqrt(2020)) + 1), x)",
    "integrate(x*(1 - x)**2020, x)",
    "integrate(sec(x)**4*tan(x)/(sec(x)**4 + 4), x)",
    "integrate(x**2*x/(2*log(x) + 2), x)",
    "integrate(sqrt(1 - x**2), x)",
    "integrate(x**5*exp(-x**4), x)",
    "integrate(tan(cos(x)), x)",
    "integrate((x + 1)/(x*(x + log(x))), x)",
    "integrate(exp(x+exp(x)) + exp(x-exp(x)), x)",
    "integrate(1/(1 - x**2), x)",
    "integrate(2/log(x), x)",
    "integrate((cos(3*x) + sin(2*x))*(-sin(2019*x) + cos(3*x)), x)",
    "integrate(cos(x)*cos(sin(x))*cos(sin(sin(x))), x)",
    "integrate(exp(-2019/(4*t**2))*t**2, x)",
    "integrate(sin(sqrt(x)), x)",
    "integrate(sqrt(x)/(1 + x), x)",
    "integrate(cos(x)*cos(2*x)*cos(3*x), x)",
    "integrate(Limit(exp(-x**(2*n)), n, oo), x)",
    "integrate(x/(1*log(x)), x)",
    "integrate((sin(20*x) + sin(19*x))/(cos(20*x) + cos(19*x)), x)",
    "integrate(exp(x)*(cos(x)**2 + cos(x)*sin(x) - sin(x)**2), x)",
    "integrate(sin(x)/sin(x + pi/4), x)",
    "integrate(1/(x + sqrt(3)*x), x)",
    "integrate(x/(x**2 + 1)*(2*log(x) + 1), x)",
    "integrate((2*x**3 - 1)/(x*(x**3 + 1)), x)",
    "integrate(cos(arctan(x)), x)"
]
